name: hackatrix
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: "^0.1.4"
  cached_network_image: "^0.4.1"
  url_launcher: "^3.0.2"
  intl: 0.15.6
  progress_hud: "^1.0.0"
  shared_preferences: "^0.4.2"
  qr_flutter: ^1.1.1
  barcode_scan: "^0.0.4"
  rxdart: "^0.18.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/hackatrix_logo.png
    - images/ic_launcher.png
    - images/ic_idea.png
    - images/ic_empty_events.png